Regroup equipmentDeletion notifications
gridsuite/study-notification-server pull request #52
Opened 2023-01-19 20:57 UTC by ayolab

Signed-off-by: Ayoub LABIDI <ayoub.labidi@protonmail.com>

2023-01-20 09:04 UTC, laurgarn approved these changes

2023-01-20 13:14 UTC, laurgarn commented
(Tested OK)

2023-01-23 14:42 UTC, archendel approved these changes

2023-01-24 08:00 UTC, etiennehomer approved these changes

2023-01-25 12:20 UTC, SlimaneAmar requested changes

2023-01-25 12:20 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/study/notification/server/payload/NetworkImpactsNotificationPayload.java
> +public class NetworkImpactsNotificationPayload {
Rename by NetworkImpactsInfos

2023-01-25 12:20 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/study/notification/server/payload/EquipmentDeletionNotification.java
> +public class EquipmentDeletionNotification {
Rename by EquipmentDeletionInfos

2023-01-25 12:20 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/study/notification/server/payload/EquipmentDeletionNotification.java
> +package org.gridsuite.study.notification.server.payload;
Rename by `dto`

2023-01-26 12:52 UTC, SlimaneAmar approved these changes

2023-01-26 13:55 UTC, merged